// Philippine Address Data for Dropdowns
// Structure: Region -> Province -> City/Municipality -> Barangay
// Includes ZIP code lookup by city

export const REGIONS = [
  { label: 'Select Region', value: '' },
  { label: 'NCR - National Capital Region', value: 'NCR' },
  { label: 'Region I - Ilocos Region', value: 'Region I' },
  { label: 'Region II - Cagayan Valley', value: 'Region II' },
  { label: 'Region III - Central Luzon', value: 'Region III' },
  { label: 'Region IV-A - CALABARZON', value: 'Region IV-A' },
  { label: 'Region IV-B - MIMAROPA', value: 'Region IV-B' },
  { label: 'Region V - Bicol Region', value: 'Region V' },
  { label: 'Region VI - Western Visayas', value: 'Region VI' },
  { label: 'Region VII - Central Visayas', value: 'Region VII' },
  { label: 'Region VIII - Eastern Visayas', value: 'Region VIII' },
  { label: 'Region IX - Zamboanga Peninsula', value: 'Region IX' },
  { label: 'Region X - Northern Mindanao', value: 'Region X' },
  { label: 'Region XI - Davao Region', value: 'Region XI' },
  { label: 'Region XII - SOCCSKSARGEN', value: 'Region XII' },
  { label: 'Region XIII - Caraga', value: 'Region XIII' },
  { label: 'CAR - Cordillera Administrative Region', value: 'CAR' },
  { label: 'BARMM - Bangsamoro', value: 'BARMM' },
];

export const PROVINCES = {
  'NCR': [
    { label: 'Select Province', value: '' },
    { label: 'Metro Manila', value: 'Metro Manila' },
  ],
  'Region I': [
    { label: 'Select Province', value: '' },
    { label: 'Ilocos Norte', value: 'Ilocos Norte' },
    { label: 'Ilocos Sur', value: 'Ilocos Sur' },
    { label: 'La Union', value: 'La Union' },
    { label: 'Pangasinan', value: 'Pangasinan' },
  ],
  'Region II': [
    { label: 'Select Province', value: '' },
    { label: 'Batanes', value: 'Batanes' },
    { label: 'Cagayan', value: 'Cagayan' },
    { label: 'Isabela', value: 'Isabela' },
    { label: 'Nueva Vizcaya', value: 'Nueva Vizcaya' },
    { label: 'Quirino', value: 'Quirino' },
  ],
  'Region III': [
    { label: 'Select Province', value: '' },
    { label: 'Aurora', value: 'Aurora' },
    { label: 'Bataan', value: 'Bataan' },
    { label: 'Bulacan', value: 'Bulacan' },
    { label: 'Nueva Ecija', value: 'Nueva Ecija' },
    { label: 'Pampanga', value: 'Pampanga' },
    { label: 'Tarlac', value: 'Tarlac' },
    { label: 'Zambales', value: 'Zambales' },
  ],
  'Region IV-A': [
    { label: 'Select Province', value: '' },
    { label: 'Batangas', value: 'Batangas' },
    { label: 'Cavite', value: 'Cavite' },
    { label: 'Laguna', value: 'Laguna' },
    { label: 'Quezon', value: 'Quezon' },
    { label: 'Rizal', value: 'Rizal' },
  ],
  'Region IV-B': [
    { label: 'Select Province', value: '' },
    { label: 'Marinduque', value: 'Marinduque' },
    { label: 'Occidental Mindoro', value: 'Occidental Mindoro' },
    { label: 'Oriental Mindoro', value: 'Oriental Mindoro' },
    { label: 'Palawan', value: 'Palawan' },
    { label: 'Romblon', value: 'Romblon' },
  ],
  'Region V': [
    { label: 'Select Province', value: '' },
    { label: 'Albay', value: 'Albay' },
    { label: 'Camarines Norte', value: 'Camarines Norte' },
    { label: 'Camarines Sur', value: 'Camarines Sur' },
    { label: 'Catanduanes', value: 'Catanduanes' },
    { label: 'Masbate', value: 'Masbate' },
    { label: 'Sorsogon', value: 'Sorsogon' },
  ],
  'Region VI': [
    { label: 'Select Province', value: '' },
    { label: 'Aklan', value: 'Aklan' },
    { label: 'Antique', value: 'Antique' },
    { label: 'Capiz', value: 'Capiz' },
    { label: 'Guimaras', value: 'Guimaras' },
    { label: 'Iloilo', value: 'Iloilo' },
    { label: 'Negros Occidental', value: 'Negros Occidental' },
  ],
  'Region VII': [
    { label: 'Select Province', value: '' },
    { label: 'Bohol', value: 'Bohol' },
    { label: 'Cebu', value: 'Cebu' },
    { label: 'Negros Oriental', value: 'Negros Oriental' },
    { label: 'Siquijor', value: 'Siquijor' },
  ],
  'Region VIII': [
    { label: 'Select Province', value: '' },
    { label: 'Biliran', value: 'Biliran' },
    { label: 'Eastern Samar', value: 'Eastern Samar' },
    { label: 'Leyte', value: 'Leyte' },
    { label: 'Northern Samar', value: 'Northern Samar' },
    { label: 'Samar', value: 'Samar' },
    { label: 'Southern Leyte', value: 'Southern Leyte' },
  ],
  'Region IX': [
    { label: 'Select Province', value: '' },
    { label: 'Zamboanga del Norte', value: 'Zamboanga del Norte' },
    { label: 'Zamboanga del Sur', value: 'Zamboanga del Sur' },
    { label: 'Zamboanga Sibugay', value: 'Zamboanga Sibugay' },
  ],
  'Region X': [
    { label: 'Select Province', value: '' },
    { label: 'Bukidnon', value: 'Bukidnon' },
    { label: 'Camiguin', value: 'Camiguin' },
    { label: 'Lanao del Norte', value: 'Lanao del Norte' },
    { label: 'Misamis Occidental', value: 'Misamis Occidental' },
    { label: 'Misamis Oriental', value: 'Misamis Oriental' },
  ],
  'Region XI': [
    { label: 'Select Province', value: '' },
    { label: 'Davao de Oro', value: 'Davao de Oro' },
    { label: 'Davao del Norte', value: 'Davao del Norte' },
    { label: 'Davao del Sur', value: 'Davao del Sur' },
    { label: 'Davao Occidental', value: 'Davao Occidental' },
    { label: 'Davao Oriental', value: 'Davao Oriental' },
  ],
  'Region XII': [
    { label: 'Select Province', value: '' },
    { label: 'Cotabato', value: 'Cotabato' },
    { label: 'Sarangani', value: 'Sarangani' },
    { label: 'South Cotabato', value: 'South Cotabato' },
    { label: 'Sultan Kudarat', value: 'Sultan Kudarat' },
  ],
  'Region XIII': [
    { label: 'Select Province', value: '' },
    { label: 'Agusan del Norte', value: 'Agusan del Norte' },
    { label: 'Agusan del Sur', value: 'Agusan del Sur' },
    { label: 'Dinagat Islands', value: 'Dinagat Islands' },
    { label: 'Surigao del Norte', value: 'Surigao del Norte' },
    { label: 'Surigao del Sur', value: 'Surigao del Sur' },
  ],
  'CAR': [
    { label: 'Select Province', value: '' },
    { label: 'Abra', value: 'Abra' },
    { label: 'Apayao', value: 'Apayao' },
    { label: 'Benguet', value: 'Benguet' },
    { label: 'Ifugao', value: 'Ifugao' },
    { label: 'Kalinga', value: 'Kalinga' },
    { label: 'Mountain Province', value: 'Mountain Province' },
  ],
  'BARMM': [
    { label: 'Select Province', value: '' },
    { label: 'Basilan', value: 'Basilan' },
    { label: 'Lanao del Sur', value: 'Lanao del Sur' },
    { label: 'Maguindanao del Norte', value: 'Maguindanao del Norte' },
    { label: 'Maguindanao del Sur', value: 'Maguindanao del Sur' },
    { label: 'Sulu', value: 'Sulu' },
    { label: 'Tawi-Tawi', value: 'Tawi-Tawi' },
  ],
};

export const CITIES = {
  // NCR - Metro Manila
  'Metro Manila': [
    { label: 'Select City/Municipality', value: '' },
    { label: 'Caloocan', value: 'Caloocan' },
    { label: 'Las Piñas', value: 'Las Piñas' },
    { label: 'Makati', value: 'Makati' },
    { label: 'Malabon', value: 'Malabon' },
    { label: 'Mandaluyong', value: 'Mandaluyong' },
    { label: 'Manila', value: 'Manila' },
    { label: 'Marikina', value: 'Marikina' },
    { label: 'Muntinlupa', value: 'Muntinlupa' },
    { label: 'Navotas', value: 'Navotas' },
    { label: 'Parañaque', value: 'Parañaque' },
    { label: 'Pasay', value: 'Pasay' },
    { label: 'Pasig', value: 'Pasig' },
    { label: 'Pateros', value: 'Pateros' },
    { label: 'Quezon City', value: 'Quezon City' },
    { label: 'San Juan', value: 'San Juan' },
    { label: 'Taguig', value: 'Taguig' },
    { label: 'Valenzuela', value: 'Valenzuela' },
  ],
  // Region I
  'Ilocos Norte': [
    { label: 'Select City/Municipality', value: '' },
    { label: 'Laoag City', value: 'Laoag City' },
    { label: 'Batac City', value: 'Batac City' },
    { label: 'Pagudpud', value: 'Pagudpud' },
    { label: 'Paoay', value: 'Paoay' },
  ],
  'Ilocos Sur': [
    { label: 'Select City/Municipality', value: '' },
    { label: 'Vigan City', value: 'Vigan City' },
    { label: 'Candon City', value: 'Candon City' },
    { label: 'Narvacan', value: 'Narvacan' },
  ],
  'La Union': [
    { label: 'Select City/Municipality', value: '' },
    { label: 'San Fernando City', value: 'San Fernando City' },
    { label: 'Bauang', value: 'Bauang' },
    { label: 'San Juan', value: 'San Juan' },
  ],
  'Pangasinan': [
    { label: 'Select City/Municipality', value: '' },
    { label: 'Dagupan City', value: 'Dagupan City' },
    { label: 'San Carlos City', value: 'San Carlos City' },
    { label: 'Alaminos City', value: 'Alaminos City' },
    { label: 'Urdaneta City', value: 'Urdaneta City' },
  ],
  // Region III
  'Bulacan': [
    { label: 'Select City/Municipality', value: '' },
    { label: 'Malolos City', value: 'Malolos City' },
    { label: 'Meycauayan City', value: 'Meycauayan City' },
    { label: 'San Jose del Monte City', value: 'San Jose del Monte City' },
    { label: 'Marilao', value: 'Marilao' },
    { label: 'Bocaue', value: 'Bocaue' },
  ],
  'Pampanga': [
    { label: 'Select City/Municipality', value: '' },
    { label: 'San Fernando City', value: 'San Fernando City' },
    { label: 'Angeles City', value: 'Angeles City' },
    { label: 'Mabalacat City', value: 'Mabalacat City' },
    { label: 'Guagua', value: 'Guagua' },
  ],
  'Nueva Ecija': [
    { label: 'Select City/Municipality', value: '' },
    { label: 'Cabanatuan City', value: 'Cabanatuan City' },
    { label: 'Palayan City', value: 'Palayan City' },
    { label: 'San Jose City', value: 'San Jose City' },
    { label: 'Gapan City', value: 'Gapan City' },
  ],
  'Tarlac': [
    { label: 'Select City/Municipality', value: '' },
    { label: 'Tarlac City', value: 'Tarlac City' },
    { label: 'Paniqui', value: 'Paniqui' },
    { label: 'Concepcion', value: 'Concepcion' },
  ],
  'Zambales': [
    { label: 'Select City/Municipality', value: '' },
    { label: 'Olongapo City', value: 'Olongapo City' },
    { label: 'Subic', value: 'Subic' },
    { label: 'Iba', value: 'Iba' },
  ],
  'Bataan': [
    { label: 'Select City/Municipality', value: '' },
    { label: 'Balanga City', value: 'Balanga City' },
    { label: 'Dinalupihan', value: 'Dinalupihan' },
    { label: 'Mariveles', value: 'Mariveles' },
  ],
  'Aurora': [
    { label: 'Select City/Municipality', value: '' },
    { label: 'Baler', value: 'Baler' },
    { label: 'Maria Aurora', value: 'Maria Aurora' },
  ],
  // Region IV-A (CALABARZON)
  'Cavite': [
    { label: 'Select City/Municipality', value: '' },
    { label: 'Bacoor City', value: 'Bacoor City' },
    { label: 'Cavite City', value: 'Cavite City' },
    { label: 'Dasmariñas City', value: 'Dasmariñas City' },
    { label: 'General Trias City', value: 'General Trias City' },
    { label: 'Imus City', value: 'Imus City' },
    { label: 'Tagaytay City', value: 'Tagaytay City' },
    { label: 'Trece Martires City', value: 'Trece Martires City' },
  ],
  'Laguna': [
    { label: 'Select City/Municipality', value: '' },
    { label: 'Biñan City', value: 'Biñan City' },
    { label: 'Cabuyao City', value: 'Cabuyao City' },
    { label: 'Calamba City', value: 'Calamba City' },
    { label: 'San Pablo City', value: 'San Pablo City' },
    { label: 'San Pedro City', value: 'San Pedro City' },
    { label: 'Santa Rosa City', value: 'Santa Rosa City' },
    { label: 'Los Baños', value: 'Los Baños' },
  ],
  'Batangas': [
    { label: 'Select City/Municipality', value: '' },
    { label: 'Batangas City', value: 'Batangas City' },
    { label: 'Lipa City', value: 'Lipa City' },
    { label: 'Tanauan City', value: 'Tanauan City' },
    { label: 'Santo Tomas City', value: 'Santo Tomas City' },
    { label: 'Nasugbu', value: 'Nasugbu' },
  ],
  'Rizal': [
    { label: 'Select City/Municipality', value: '' },
    { label: 'Antipolo City', value: 'Antipolo City' },
    { label: 'Cainta', value: 'Cainta' },
    { label: 'Taytay', value: 'Taytay' },
    { label: 'Angono', value: 'Angono' },
    { label: 'Binangonan', value: 'Binangonan' },
  ],
  'Quezon': [
    { label: 'Select City/Municipality', value: '' },
    { label: 'Lucena City', value: 'Lucena City' },
    { label: 'Tayabas City', value: 'Tayabas City' },
    { label: 'Sariaya', value: 'Sariaya' },
    { label: 'Pagbilao', value: 'Pagbilao' },
  ],
  // Region VII
  'Cebu': [
    { label: 'Select City/Municipality', value: '' },
    { label: 'Cebu City', value: 'Cebu City' },
    { label: 'Lapu-Lapu City', value: 'Lapu-Lapu City' },
    { label: 'Mandaue City', value: 'Mandaue City' },
    { label: 'Talisay City', value: 'Talisay City' },
    { label: 'Toledo City', value: 'Toledo City' },
  ],
  'Bohol': [
    { label: 'Select City/Municipality', value: '' },
    { label: 'Tagbilaran City', value: 'Tagbilaran City' },
    { label: 'Panglao', value: 'Panglao' },
    { label: 'Loboc', value: 'Loboc' },
  ],
  // Region XI
  'Davao del Sur': [
    { label: 'Select City/Municipality', value: '' },
    { label: 'Davao City', value: 'Davao City' },
    { label: 'Digos City', value: 'Digos City' },
    { label: 'Bansalan', value: 'Bansalan' },
  ],
  'Davao del Norte': [
    { label: 'Select City/Municipality', value: '' },
    { label: 'Tagum City', value: 'Tagum City' },
    { label: 'Panabo City', value: 'Panabo City' },
    { label: 'Samal City', value: 'Samal City' },
  ],
};

export const BARANGAYS = {
  // NCR - Metro Manila
  'Quezon City': [
    { label: 'Select Barangay', value: '' },
    { label: 'Bagong Pag-Asa', value: 'Bagong Pag-Asa' },
    { label: 'Batasan Hills', value: 'Batasan Hills' },
    { label: 'Commonwealth', value: 'Commonwealth' },
    { label: 'Diliman', value: 'Diliman' },
    { label: 'Fairview', value: 'Fairview' },
    { label: 'Holy Spirit', value: 'Holy Spirit' },
    { label: 'Kamuning', value: 'Kamuning' },
    { label: 'Novaliches', value: 'Novaliches' },
    { label: 'Project 6', value: 'Project 6' },
    { label: 'Tandang Sora', value: 'Tandang Sora' },
  ],
  'Makati': [
    { label: 'Select Barangay', value: '' },
    { label: 'Bel-Air', value: 'Bel-Air' },
    { label: 'Forbes Park', value: 'Forbes Park' },
    { label: 'Guadalupe Nuevo', value: 'Guadalupe Nuevo' },
    { label: 'Guadalupe Viejo', value: 'Guadalupe Viejo' },
    { label: 'Legaspi', value: 'Legaspi' },
    { label: 'Poblacion', value: 'Poblacion' },
    { label: 'San Antonio', value: 'San Antonio' },
    { label: 'Urdaneta', value: 'Urdaneta' },
  ],
  'Manila': [
    { label: 'Select Barangay', value: '' },
    { label: 'Binondo', value: 'Binondo' },
    { label: 'Ermita', value: 'Ermita' },
    { label: 'Intramuros', value: 'Intramuros' },
    { label: 'Malate', value: 'Malate' },
    { label: 'Paco', value: 'Paco' },
    { label: 'Pandacan', value: 'Pandacan' },
    { label: 'Quiapo', value: 'Quiapo' },
    { label: 'Sampaloc', value: 'Sampaloc' },
    { label: 'San Miguel', value: 'San Miguel' },
    { label: 'Santa Ana', value: 'Santa Ana' },
    { label: 'Tondo', value: 'Tondo' },
  ],
  'Taguig': [
    { label: 'Select Barangay', value: '' },
    { label: 'Bagumbayan', value: 'Bagumbayan' },
    { label: 'Bambang', value: 'Bambang' },
    { label: 'Fort Bonifacio', value: 'Fort Bonifacio' },
    { label: 'Pinagsama', value: 'Pinagsama' },
    { label: 'Signal Village', value: 'Signal Village' },
    { label: 'Ususan', value: 'Ususan' },
    { label: 'Western Bicutan', value: 'Western Bicutan' },
  ],
  'Pasig': [
    { label: 'Select Barangay', value: '' },
    { label: 'Bagong Ilog', value: 'Bagong Ilog' },
    { label: 'Kapitolyo', value: 'Kapitolyo' },
    { label: 'Manggahan', value: 'Manggahan' },
    { label: 'Ortigas Center', value: 'Ortigas Center' },
    { label: 'Rosario', value: 'Rosario' },
    { label: 'San Antonio', value: 'San Antonio' },
    { label: 'Santolan', value: 'Santolan' },
  ],
  'Caloocan': [
    { label: 'Select Barangay', value: '' },
    { label: 'Bagong Barrio', value: 'Bagong Barrio' },
    { label: 'Camarin', value: 'Camarin' },
    { label: 'Grace Park', value: 'Grace Park' },
    { label: 'Maypajo', value: 'Maypajo' },
    { label: 'Sangandaan', value: 'Sangandaan' },
  ],
  // CALABARZON
  'Calamba City': [
    { label: 'Select Barangay', value: '' },
    { label: 'Bagong Kalsada', value: 'Bagong Kalsada' },
    { label: 'Barandal', value: 'Barandal' },
    { label: 'Bucal', value: 'Bucal' },
    { label: 'Canlubang', value: 'Canlubang' },
    { label: 'Halang', value: 'Halang' },
    { label: 'Lawa', value: 'Lawa' },
    { label: 'Parian', value: 'Parian' },
    { label: 'Real', value: 'Real' },
  ],
  'Santa Rosa City': [
    { label: 'Select Barangay', value: '' },
    { label: 'Balibago', value: 'Balibago' },
    { label: 'Dita', value: 'Dita' },
    { label: 'Ibaba', value: 'Ibaba' },
    { label: 'Macabling', value: 'Macabling' },
    { label: 'Malusak', value: 'Malusak' },
    { label: 'Tagapo', value: 'Tagapo' },
  ],
  'Antipolo City': [
    { label: 'Select Barangay', value: '' },
    { label: 'Bagong Nayon', value: 'Bagong Nayon' },
    { label: 'Beverly Hills', value: 'Beverly Hills' },
    { label: 'Cupang', value: 'Cupang' },
    { label: 'Dela Paz', value: 'Dela Paz' },
    { label: 'Mambugan', value: 'Mambugan' },
    { label: 'Mayamot', value: 'Mayamot' },
    { label: 'San Jose', value: 'San Jose' },
    { label: 'San Roque', value: 'San Roque' },
  ],
  'Dasmariñas City': [
    { label: 'Select Barangay', value: '' },
    { label: 'Burol', value: 'Burol' },
    { label: 'Langkaan', value: 'Langkaan' },
    { label: 'Paliparan', value: 'Paliparan' },
    { label: 'Sabang', value: 'Sabang' },
    { label: 'Salawag', value: 'Salawag' },
    { label: 'Sampaloc', value: 'Sampaloc' },
    { label: 'San Agustin', value: 'San Agustin' },
  ],
  'Bacoor City': [
    { label: 'Select Barangay', value: '' },
    { label: 'Alima', value: 'Alima' },
    { label: 'Aniban', value: 'Aniban' },
    { label: 'Habay', value: 'Habay' },
    { label: 'Molino', value: 'Molino' },
    { label: 'Niog', value: 'Niog' },
    { label: 'Panapaan', value: 'Panapaan' },
    { label: 'Talaba', value: 'Talaba' },
  ],
  // Cebu
  'Cebu City': [
    { label: 'Select Barangay', value: '' },
    { label: 'Apas', value: 'Apas' },
    { label: 'Banilad', value: 'Banilad' },
    { label: 'Capitol Site', value: 'Capitol Site' },
    { label: 'Guadalupe', value: 'Guadalupe' },
    { label: 'Lahug', value: 'Lahug' },
    { label: 'Mabolo', value: 'Mabolo' },
    { label: 'Talamban', value: 'Talamban' },
  ],
  // Davao
  'Davao City': [
    { label: 'Select Barangay', value: '' },
    { label: 'Agdao', value: 'Agdao' },
    { label: 'Bajada', value: 'Bajada' },
    { label: 'Buhangin', value: 'Buhangin' },
    { label: 'Lanang', value: 'Lanang' },
    { label: 'Matina', value: 'Matina' },
    { label: 'Poblacion', value: 'Poblacion' },
    { label: 'Talomo', value: 'Talomo' },
    { label: 'Toril', value: 'Toril' },
  ],
  // Additional NCR Cities
  'Parañaque': [
    { label: 'Select Barangay', value: '' },
    { label: 'Baclaran', value: 'Baclaran' },
    { label: 'BF Homes', value: 'BF Homes' },
    { label: 'Don Bosco', value: 'Don Bosco' },
    { label: 'La Huerta', value: 'La Huerta' },
    { label: 'Merville', value: 'Merville' },
    { label: 'Moonwalk', value: 'Moonwalk' },
    { label: 'San Antonio', value: 'San Antonio' },
    { label: 'San Dionisio', value: 'San Dionisio' },
    { label: 'San Isidro', value: 'San Isidro' },
    { label: 'San Martin de Porres', value: 'San Martin de Porres' },
    { label: 'Sucat', value: 'Sucat' },
    { label: 'Tambo', value: 'Tambo' },
  ],
  'Las Piñas': [
    { label: 'Select Barangay', value: '' },
    { label: 'Almanza Uno', value: 'Almanza Uno' },
    { label: 'Almanza Dos', value: 'Almanza Dos' },
    { label: 'BF International', value: 'BF International' },
    { label: 'CAA', value: 'CAA' },
    { label: 'Daniel Fajardo', value: 'Daniel Fajardo' },
    { label: 'Elias Aldana', value: 'Elias Aldana' },
    { label: 'Ilaya', value: 'Ilaya' },
    { label: 'Manuyo Uno', value: 'Manuyo Uno' },
    { label: 'Manuyo Dos', value: 'Manuyo Dos' },
    { label: 'Pamplona Uno', value: 'Pamplona Uno' },
    { label: 'Pamplona Dos', value: 'Pamplona Dos' },
    { label: 'Pamplona Tres', value: 'Pamplona Tres' },
    { label: 'Pilar', value: 'Pilar' },
    { label: 'Pulang Lupa Uno', value: 'Pulang Lupa Uno' },
    { label: 'Pulang Lupa Dos', value: 'Pulang Lupa Dos' },
    { label: 'Talon Uno', value: 'Talon Uno' },
    { label: 'Talon Dos', value: 'Talon Dos' },
    { label: 'Talon Tres', value: 'Talon Tres' },
    { label: 'Talon Kuatro', value: 'Talon Kuatro' },
    { label: 'Talon Singko', value: 'Talon Singko' },
    { label: 'Zapote', value: 'Zapote' },
  ],
  'Muntinlupa': [
    { label: 'Select Barangay', value: '' },
    { label: 'Alabang', value: 'Alabang' },
    { label: 'Ayala Alabang', value: 'Ayala Alabang' },
    { label: 'Bayanan', value: 'Bayanan' },
    { label: 'Buli', value: 'Buli' },
    { label: 'Cupang', value: 'Cupang' },
    { label: 'Poblacion', value: 'Poblacion' },
    { label: 'Putatan', value: 'Putatan' },
    { label: 'Sucat', value: 'Sucat' },
    { label: 'Tunasan', value: 'Tunasan' },
  ],
  'Mandaluyong': [
    { label: 'Select Barangay', value: '' },
    { label: 'Addition Hills', value: 'Addition Hills' },
    { label: 'Bagong Silang', value: 'Bagong Silang' },
    { label: 'Barangka', value: 'Barangka' },
    { label: 'Buayang Bato', value: 'Buayang Bato' },
    { label: 'Highway Hills', value: 'Highway Hills' },
    { label: 'Hulo', value: 'Hulo' },
    { label: 'Mabini-J. Rizal', value: 'Mabini-J. Rizal' },
    { label: 'Malamig', value: 'Malamig' },
    { label: 'Mauway', value: 'Mauway' },
    { label: 'Namayan', value: 'Namayan' },
    { label: 'New Zañiga', value: 'New Zañiga' },
    { label: 'Old Zañiga', value: 'Old Zañiga' },
    { label: 'Pag-asa', value: 'Pag-asa' },
    { label: 'Plainview', value: 'Plainview' },
    { label: 'Pleasant Hills', value: 'Pleasant Hills' },
    { label: 'Poblacion', value: 'Poblacion' },
    { label: 'San Jose', value: 'San Jose' },
    { label: 'Vergara', value: 'Vergara' },
    { label: 'Wack-Wack Greenhills', value: 'Wack-Wack Greenhills' },
  ],
  'San Juan': [
    { label: 'Select Barangay', value: '' },
    { label: 'Addition Hills', value: 'Addition Hills' },
    { label: 'Balong-Bato', value: 'Balong-Bato' },
    { label: 'Batis', value: 'Batis' },
    { label: 'Corazon de Jesus', value: 'Corazon de Jesus' },
    { label: 'Ermitaño', value: 'Ermitaño' },
    { label: 'Greenhills', value: 'Greenhills' },
    { label: 'Isabelita', value: 'Isabelita' },
    { label: 'Kabayanan', value: 'Kabayanan' },
    { label: 'Little Baguio', value: 'Little Baguio' },
    { label: 'Maytunas', value: 'Maytunas' },
    { label: 'Onse', value: 'Onse' },
    { label: 'Pasadeña', value: 'Pasadeña' },
    { label: 'Pedro Cruz', value: 'Pedro Cruz' },
    { label: 'Progreso', value: 'Progreso' },
    { label: 'Rivera', value: 'Rivera' },
    { label: 'Salapan', value: 'Salapan' },
    { label: 'San Perfecto', value: 'San Perfecto' },
    { label: 'Santa Lucia', value: 'Santa Lucia' },
    { label: 'Tibagan', value: 'Tibagan' },
    { label: 'West Crame', value: 'West Crame' },
  ],
  'Marikina': [
    { label: 'Select Barangay', value: '' },
    { label: 'Barangka', value: 'Barangka' },
    { label: 'Calumpang', value: 'Calumpang' },
    { label: 'Concepcion Uno', value: 'Concepcion Uno' },
    { label: 'Concepcion Dos', value: 'Concepcion Dos' },
    { label: 'Fortune', value: 'Fortune' },
    { label: 'Industrial Valley', value: 'Industrial Valley' },
    { label: 'Jesus dela Peña', value: 'Jesus dela Peña' },
    { label: 'Malanday', value: 'Malanday' },
    { label: 'Nangka', value: 'Nangka' },
    { label: 'Parang', value: 'Parang' },
    { label: 'San Roque', value: 'San Roque' },
    { label: 'Santa Elena', value: 'Santa Elena' },
    { label: 'Santo Niño', value: 'Santo Niño' },
    { label: 'Tañong', value: 'Tañong' },
    { label: 'Tumana', value: 'Tumana' },
  ],
  'Pasay': [
    { label: 'Select Barangay', value: '' },
    { label: 'Baclaran', value: 'Baclaran' },
    { label: 'Bay City', value: 'Bay City' },
    { label: 'Cartimar', value: 'Cartimar' },
    { label: 'Don Carlos', value: 'Don Carlos' },
    { label: 'La Huerta', value: 'La Huerta' },
    { label: 'Malibay', value: 'Malibay' },
    { label: 'Newport City', value: 'Newport City' },
    { label: 'Pasay Rotonda', value: 'Pasay Rotonda' },
    { label: 'San Isidro', value: 'San Isidro' },
    { label: 'San Jose', value: 'San Jose' },
    { label: 'San Rafael', value: 'San Rafael' },
    { label: 'Santa Clara', value: 'Santa Clara' },
    { label: 'Villamor', value: 'Villamor' },
  ],
  'Valenzuela': [
    { label: 'Select Barangay', value: '' },
    { label: 'Arkong Bato', value: 'Arkong Bato' },
    { label: 'Balangkas', value: 'Balangkas' },
    { label: 'Bignay', value: 'Bignay' },
    { label: 'Bisig', value: 'Bisig' },
    { label: 'Canumay East', value: 'Canumay East' },
    { label: 'Canumay West', value: 'Canumay West' },
    { label: 'Coloong', value: 'Coloong' },
    { label: 'Dalandanan', value: 'Dalandanan' },
    { label: 'Gen. T. de Leon', value: 'Gen. T. de Leon' },
    { label: 'Isla', value: 'Isla' },
    { label: 'Karuhatan', value: 'Karuhatan' },
    { label: 'Lawang Bato', value: 'Lawang Bato' },
    { label: 'Lingunan', value: 'Lingunan' },
    { label: 'Mabolo', value: 'Mabolo' },
    { label: 'Malanday', value: 'Malanday' },
    { label: 'Malinta', value: 'Malinta' },
    { label: 'Mapulang Lupa', value: 'Mapulang Lupa' },
    { label: 'Marulas', value: 'Marulas' },
    { label: 'Maysan', value: 'Maysan' },
    { label: 'Palasan', value: 'Palasan' },
    { label: 'Parada', value: 'Parada' },
    { label: 'Pariancillo Villa', value: 'Pariancillo Villa' },
    { label: 'Paso de Blas', value: 'Paso de Blas' },
    { label: 'Pasolo', value: 'Pasolo' },
    { label: 'Poblacion', value: 'Poblacion' },
    { label: 'Polo', value: 'Polo' },
    { label: 'Punturin', value: 'Punturin' },
    { label: 'Rincon', value: 'Rincon' },
    { label: 'Tagalag', value: 'Tagalag' },
    { label: 'Ugong', value: 'Ugong' },
    { label: 'Viente Reales', value: 'Viente Reales' },
    { label: 'Wawang Pulo', value: 'Wawang Pulo' },
  ],
  'Navotas': [
    { label: 'Select Barangay', value: '' },
    { label: 'Bagumbayan North', value: 'Bagumbayan North' },
    { label: 'Bagumbayan South', value: 'Bagumbayan South' },
    { label: 'Bangculasi', value: 'Bangculasi' },
    { label: 'Daanghari', value: 'Daanghari' },
    { label: 'Navotas East', value: 'Navotas East' },
    { label: 'Navotas West', value: 'Navotas West' },
    { label: 'North Bay Boulevard North', value: 'North Bay Boulevard North' },
    { label: 'North Bay Boulevard South', value: 'North Bay Boulevard South' },
    { label: 'San Jose', value: 'San Jose' },
    { label: 'San Rafael Village', value: 'San Rafael Village' },
    { label: 'San Roque', value: 'San Roque' },
    { label: 'Sipac-Almacen', value: 'Sipac-Almacen' },
    { label: 'Tangos', value: 'Tangos' },
    { label: 'Tanza', value: 'Tanza' },
  ],
  'Malabon': [
    { label: 'Select Barangay', value: '' },
    { label: 'Acacia', value: 'Acacia' },
    { label: 'Baritan', value: 'Baritan' },
    { label: 'Bayan-bayanan', value: 'Bayan-bayanan' },
    { label: 'Catmon', value: 'Catmon' },
    { label: 'Concepcion', value: 'Concepcion' },
    { label: 'Dampalit', value: 'Dampalit' },
    { label: 'Flores', value: 'Flores' },
    { label: 'Hulong Duhat', value: 'Hulong Duhat' },
    { label: 'Ibaba', value: 'Ibaba' },
    { label: 'Longos', value: 'Longos' },
    { label: 'Maysilo', value: 'Maysilo' },
    { label: 'Muzon', value: 'Muzon' },
    { label: 'Niugan', value: 'Niugan' },
    { label: 'Panghulo', value: 'Panghulo' },
    { label: 'Potrero', value: 'Potrero' },
    { label: 'San Agustin', value: 'San Agustin' },
    { label: 'Santolan', value: 'Santolan' },
    { label: 'Tanong', value: 'Tanong' },
    { label: 'Tinajeros', value: 'Tinajeros' },
    { label: 'Tonsuya', value: 'Tonsuya' },
    { label: 'Tugatog', value: 'Tugatog' },
  ],
  'Pateros': [
    { label: 'Select Barangay', value: '' },
    { label: 'Aguho', value: 'Aguho' },
    { label: 'Magtanggol', value: 'Magtanggol' },
    { label: 'Martires del 96', value: 'Martires del 96' },
    { label: 'Poblacion', value: 'Poblacion' },
    { label: 'San Pedro', value: 'San Pedro' },
    { label: 'San Roque', value: 'San Roque' },
    { label: 'Santa Ana', value: 'Santa Ana' },
    { label: 'Santo Rosario-Kanluran', value: 'Santo Rosario-Kanluran' },
    { label: 'Santo Rosario-Silangan', value: 'Santo Rosario-Silangan' },
    { label: 'Tabacalera', value: 'Tabacalera' },
  ],
  // Additional CALABARZON
  'Imus City': [
    { label: 'Select Barangay', value: '' },
    { label: 'Alapan I-A', value: 'Alapan I-A' },
    { label: 'Alapan I-B', value: 'Alapan I-B' },
    { label: 'Alapan I-C', value: 'Alapan I-C' },
    { label: 'Alapan II-A', value: 'Alapan II-A' },
    { label: 'Alapan II-B', value: 'Alapan II-B' },
    { label: 'Anabu I-A', value: 'Anabu I-A' },
    { label: 'Anabu I-B', value: 'Anabu I-B' },
    { label: 'Anabu I-C', value: 'Anabu I-C' },
    { label: 'Anabu I-D', value: 'Anabu I-D' },
    { label: 'Anabu I-E', value: 'Anabu I-E' },
    { label: 'Anabu I-F', value: 'Anabu I-F' },
    { label: 'Anabu I-G', value: 'Anabu I-G' },
    { label: 'Anabu II-A', value: 'Anabu II-A' },
    { label: 'Anabu II-B', value: 'Anabu II-B' },
    { label: 'Anabu II-C', value: 'Anabu II-C' },
    { label: 'Anabu II-D', value: 'Anabu II-D' },
    { label: 'Anabu II-E', value: 'Anabu II-E' },
    { label: 'Anabu II-F', value: 'Anabu II-F' },
    { label: 'Bayan Luma I', value: 'Bayan Luma I' },
    { label: 'Bayan Luma II', value: 'Bayan Luma II' },
    { label: 'Bayan Luma III', value: 'Bayan Luma III' },
    { label: 'Bayan Luma IV', value: 'Bayan Luma IV' },
    { label: 'Bayan Luma V', value: 'Bayan Luma V' },
    { label: 'Bayan Luma VI', value: 'Bayan Luma VI' },
    { label: 'Bayan Luma VII', value: 'Bayan Luma VII' },
    { label: 'Bayan Luma VIII', value: 'Bayan Luma VIII' },
    { label: 'Bayan Luma IX', value: 'Bayan Luma IX' },
    { label: 'Bucandala I', value: 'Bucandala I' },
    { label: 'Bucandala II', value: 'Bucandala II' },
    { label: 'Bucandala III', value: 'Bucandala III' },
    { label: 'Bucandala IV', value: 'Bucandala IV' },
    { label: 'Bucandala V', value: 'Bucandala V' },
    { label: 'Buhay na Tubig', value: 'Buhay na Tubig' },
    { label: 'Carsadang Bago I', value: 'Carsadang Bago I' },
    { label: 'Carsadang Bago II', value: 'Carsadang Bago II' },
    { label: 'Magdalo', value: 'Magdalo' },
    { label: 'Malagasang I-A', value: 'Malagasang I-A' },
    { label: 'Malagasang I-B', value: 'Malagasang I-B' },
    { label: 'Malagasang I-C', value: 'Malagasang I-C' },
    { label: 'Malagasang I-D', value: 'Malagasang I-D' },
    { label: 'Malagasang I-E', value: 'Malagasang I-E' },
    { label: 'Malagasang I-F', value: 'Malagasang I-F' },
    { label: 'Malagasang I-G', value: 'Malagasang I-G' },
    { label: 'Malagasang II-A', value: 'Malagasang II-A' },
    { label: 'Malagasang II-B', value: 'Malagasang II-B' },
    { label: 'Malagasang II-C', value: 'Malagasang II-C' },
    { label: 'Malagasang II-D', value: 'Malagasang II-D' },
    { label: 'Malagasang II-E', value: 'Malagasang II-E' },
    { label: 'Malagasang II-F', value: 'Malagasang II-F' },
    { label: 'Malagasang II-G', value: 'Malagasang II-G' },
    { label: 'Mariano Espeleta I', value: 'Mariano Espeleta I' },
    { label: 'Mariano Espeleta II', value: 'Mariano Espeleta II' },
    { label: 'Mariano Espeleta III', value: 'Mariano Espeleta III' },
    { label: 'Medicion I-A', value: 'Medicion I-A' },
    { label: 'Medicion I-B', value: 'Medicion I-B' },
    { label: 'Medicion I-C', value: 'Medicion I-C' },
    { label: 'Medicion I-D', value: 'Medicion I-D' },
    { label: 'Medicion II-A', value: 'Medicion II-A' },
    { label: 'Medicion II-B', value: 'Medicion II-B' },
    { label: 'Medicion II-C', value: 'Medicion II-C' },
    { label: 'Medicion II-D', value: 'Medicion II-D' },
    { label: 'Medicion II-E', value: 'Medicion II-E' },
    { label: 'Medicion II-F', value: 'Medicion II-F' },
    { label: 'Pag-asa I', value: 'Pag-asa I' },
    { label: 'Pag-asa II', value: 'Pag-asa II' },
    { label: 'Pag-asa III', value: 'Pag-asa III' },
    { label: 'Palico I', value: 'Palico I' },
    { label: 'Palico II', value: 'Palico II' },
    { label: 'Palico III', value: 'Palico III' },
    { label: 'Palico IV', value: 'Palico IV' },
    { label: 'Pasong Buaya I', value: 'Pasong Buaya I' },
    { label: 'Pasong Buaya II', value: 'Pasong Buaya II' },
    { label: 'Pinagbuklod', value: 'Pinagbuklod' },
    { label: 'Poblacion I-A', value: 'Poblacion I-A' },
    { label: 'Poblacion I-B', value: 'Poblacion I-B' },
    { label: 'Poblacion I-C', value: 'Poblacion I-C' },
    { label: 'Poblacion II-A', value: 'Poblacion II-A' },
    { label: 'Poblacion II-B', value: 'Poblacion II-B' },
    { label: 'Poblacion III-A', value: 'Poblacion III-A' },
    { label: 'Poblacion III-B', value: 'Poblacion III-B' },
    { label: 'Poblacion IV-A', value: 'Poblacion IV-A' },
    { label: 'Poblacion IV-B', value: 'Poblacion IV-B' },
    { label: 'Poblacion IV-C', value: 'Poblacion IV-C' },
    { label: 'Poblacion IV-D', value: 'Poblacion IV-D' },
    { label: 'Tanzang Luma I', value: 'Tanzang Luma I' },
    { label: 'Tanzang Luma II', value: 'Tanzang Luma II' },
    { label: 'Tanzang Luma III', value: 'Tanzang Luma III' },
    { label: 'Tanzang Luma IV', value: 'Tanzang Luma IV' },
    { label: 'Tanzang Luma V', value: 'Tanzang Luma V' },
    { label: 'Tanzang Luma VI', value: 'Tanzang Luma VI' },
    { label: 'Toclong I-A', value: 'Toclong I-A' },
    { label: 'Toclong I-B', value: 'Toclong I-B' },
    { label: 'Toclong I-C', value: 'Toclong I-C' },
    { label: 'Toclong II-A', value: 'Toclong II-A' },
    { label: 'Toclong II-B', value: 'Toclong II-B' },
  ],
  'General Trias City': [
    { label: 'Select Barangay', value: '' },
    { label: 'Alingaro', value: 'Alingaro' },
    { label: 'Arnaldo Poblacion', value: 'Arnaldo Poblacion' },
    { label: 'Bacao I', value: 'Bacao I' },
    { label: 'Bacao II', value: 'Bacao II' },
    { label: 'Bagumbayan Poblacion', value: 'Bagumbayan Poblacion' },
    { label: 'Biclatan', value: 'Biclatan' },
    { label: 'Buenavista I', value: 'Buenavista I' },
    { label: 'Buenavista II', value: 'Buenavista II' },
    { label: 'Buenavista III', value: 'Buenavista III' },
    { label: 'Corregidor Poblacion', value: 'Corregidor Poblacion' },
    { label: 'Dulong Bayan Poblacion', value: 'Dulong Bayan Poblacion' },
    { label: 'Governor Ferrer Poblacion', value: 'Governor Ferrer Poblacion' },
    { label: 'Javalera', value: 'Javalera' },
    { label: 'Manggahan', value: 'Manggahan' },
    { label: 'Navarro', value: 'Navarro' },
    { label: 'Ninety Sixth Poblacion', value: 'Ninety Sixth Poblacion' },
    { label: 'Panungyanan', value: 'Panungyanan' },
    { label: 'Pasong Camachile I', value: 'Pasong Camachile I' },
    { label: 'Pasong Camachile II', value: 'Pasong Camachile II' },
    { label: 'Pasong Kawayan I', value: 'Pasong Kawayan I' },
    { label: 'Pasong Kawayan II', value: 'Pasong Kawayan II' },
    { label: 'Pinagtipunan', value: 'Pinagtipunan' },
    { label: 'Prinza Poblacion', value: 'Prinza Poblacion' },
    { label: 'San Francisco', value: 'San Francisco' },
    { label: 'San Gabriel Poblacion', value: 'San Gabriel Poblacion' },
    { label: 'San Juan I', value: 'San Juan I' },
    { label: 'San Juan II', value: 'San Juan II' },
    { label: 'Santa Clara', value: 'Santa Clara' },
    { label: 'Santiago', value: 'Santiago' },
    { label: 'Tapia', value: 'Tapia' },
    { label: 'Tejero', value: 'Tejero' },
    { label: 'Vibora Poblacion', value: 'Vibora Poblacion' },
  ],
  'Biñan City': [
    { label: 'Select Barangay', value: '' },
    { label: 'Biñan (Poblacion)', value: 'Biñan (Poblacion)' },
    { label: 'Bungahan', value: 'Bungahan' },
    { label: 'Canlalay', value: 'Canlalay' },
    { label: 'Casile', value: 'Casile' },
    { label: 'De La Paz', value: 'De La Paz' },
    { label: 'Ganado', value: 'Ganado' },
    { label: 'Langkiwa', value: 'Langkiwa' },
    { label: 'Loma', value: 'Loma' },
    { label: 'Malaban', value: 'Malaban' },
    { label: 'Malamig', value: 'Malamig' },
    { label: 'Mamplasan', value: 'Mamplasan' },
    { label: 'Platero', value: 'Platero' },
    { label: 'Poblacion', value: 'Poblacion' },
    { label: 'San Antonio', value: 'San Antonio' },
    { label: 'San Francisco', value: 'San Francisco' },
    { label: 'San Jose', value: 'San Jose' },
    { label: 'San Vicente', value: 'San Vicente' },
    { label: 'Santo Domingo', value: 'Santo Domingo' },
    { label: 'Santo Niño', value: 'Santo Niño' },
    { label: 'Santo Tomas', value: 'Santo Tomas' },
    { label: 'Soro-soro', value: 'Soro-soro' },
    { label: 'Timbao', value: 'Timbao' },
    { label: 'Tubigan', value: 'Tubigan' },
    { label: 'Zapote', value: 'Zapote' },
  ],
  'San Pedro City': [
    { label: 'Select Barangay', value: '' },
    { label: 'Bagong Silang', value: 'Bagong Silang' },
    { label: 'Calendola', value: 'Calendola' },
    { label: 'Chrysanthemum', value: 'Chrysanthemum' },
    { label: 'Cuyab', value: 'Cuyab' },
    { label: 'Estrella', value: 'Estrella' },
    { label: 'Fatima', value: 'Fatima' },
    { label: 'G.S.I.S.', value: 'G.S.I.S.' },
    { label: 'Landayan', value: 'Landayan' },
    { label: 'Langgam', value: 'Langgam' },
    { label: 'Laram', value: 'Laram' },
    { label: 'Magsaysay', value: 'Magsaysay' },
    { label: 'Maharlika', value: 'Maharlika' },
    { label: 'Narra', value: 'Narra' },
    { label: 'Nueva', value: 'Nueva' },
    { label: 'Pacita 1', value: 'Pacita 1' },
    { label: 'Pacita 2', value: 'Pacita 2' },
    { label: 'Poblacion', value: 'Poblacion' },
    { label: 'Riverside', value: 'Riverside' },
    { label: 'Rosario', value: 'Rosario' },
    { label: 'Sampaguita Village', value: 'Sampaguita Village' },
    { label: 'San Antonio', value: 'San Antonio' },
    { label: 'San Lorenzo Ruiz', value: 'San Lorenzo Ruiz' },
    { label: 'San Roque', value: 'San Roque' },
    { label: 'San Vicente', value: 'San Vicente' },
    { label: 'Santo Niño', value: 'Santo Niño' },
    { label: 'United Bayanihan', value: 'United Bayanihan' },
    { label: 'United Better Living', value: 'United Better Living' },
  ],
  'Cabuyao City': [
    { label: 'Select Barangay', value: '' },
    { label: 'Baclaran', value: 'Baclaran' },
    { label: 'Banay-Banay', value: 'Banay-Banay' },
    { label: 'Banlic', value: 'Banlic' },
    { label: 'Bigaa', value: 'Bigaa' },
    { label: 'Butong', value: 'Butong' },
    { label: 'Casile', value: 'Casile' },
    { label: 'Diezmo', value: 'Diezmo' },
    { label: 'Gulod', value: 'Gulod' },
    { label: 'Mamatid', value: 'Mamatid' },
    { label: 'Marinig', value: 'Marinig' },
    { label: 'Niugan', value: 'Niugan' },
    { label: 'Pittland', value: 'Pittland' },
    { label: 'Poblacion Uno', value: 'Poblacion Uno' },
    { label: 'Poblacion Dos', value: 'Poblacion Dos' },
    { label: 'Poblacion Tres', value: 'Poblacion Tres' },
    { label: 'Pulo', value: 'Pulo' },
    { label: 'Sala', value: 'Sala' },
    { label: 'San Isidro', value: 'San Isidro' },
  ],
  'Los Baños': [
    { label: 'Select Barangay', value: '' },
    { label: 'Anos', value: 'Anos' },
    { label: 'Bagong Silang', value: 'Bagong Silang' },
    { label: 'Bambang', value: 'Bambang' },
    { label: 'Batong Malake', value: 'Batong Malake' },
    { label: 'Baybayin', value: 'Baybayin' },
    { label: 'Bayog', value: 'Bayog' },
    { label: 'Lalakay', value: 'Lalakay' },
    { label: 'Maahas', value: 'Maahas' },
    { label: 'Malinta', value: 'Malinta' },
    { label: 'Mayondon', value: 'Mayondon' },
    { label: 'Poblacion', value: 'Poblacion' },
    { label: 'Putho-Tuntungin', value: 'Putho-Tuntungin' },
    { label: 'San Antonio', value: 'San Antonio' },
    { label: 'Tadlak', value: 'Tadlak' },
    { label: 'Timugan', value: 'Timugan' },
  ],
  // Additional Rizal
  'Cainta': [
    { label: 'Select Barangay', value: '' },
    { label: 'San Andres', value: 'San Andres' },
    { label: 'San Isidro', value: 'San Isidro' },
    { label: 'San Juan', value: 'San Juan' },
    { label: 'San Roque', value: 'San Roque' },
    { label: 'Santa Rosa', value: 'Santa Rosa' },
    { label: 'Santo Domingo', value: 'Santo Domingo' },
    { label: 'Santo Niño', value: 'Santo Niño' },
  ],
  'Taytay': [
    { label: 'Select Barangay', value: '' },
    { label: 'Dolores', value: 'Dolores' },
    { label: 'Muzon', value: 'Muzon' },
    { label: 'San Isidro', value: 'San Isidro' },
    { label: 'San Juan', value: 'San Juan' },
    { label: 'Santa Ana', value: 'Santa Ana' },
    { label: 'Tipas', value: 'Tipas' },
  ],
  // Additional Bulacan
  'Malolos City': [
    { label: 'Select Barangay', value: '' },
    { label: 'Atlag', value: 'Atlag' },
    { label: 'Balite', value: 'Balite' },
    { label: 'Banga', value: 'Banga' },
    { label: 'Bulihan', value: 'Bulihan' },
    { label: 'Caliligawan', value: 'Caliligawan' },
    { label: 'Canalate', value: 'Canalate' },
    { label: 'Catmon', value: 'Catmon' },
    { label: 'Cofradia', value: 'Cofradia' },
    { label: 'Dakila', value: 'Dakila' },
    { label: 'Guinhawa', value: 'Guinhawa' },
    { label: 'Ligas', value: 'Ligas' },
    { label: 'Longos', value: 'Longos' },
    { label: 'Look 1st', value: 'Look 1st' },
    { label: 'Look 2nd', value: 'Look 2nd' },
    { label: 'Lugam', value: 'Lugam' },
    { label: 'Mabolo', value: 'Mabolo' },
    { label: 'Mambog', value: 'Mambog' },
    { label: 'Masile', value: 'Masile' },
    { label: 'Matimbo', value: 'Matimbo' },
    { label: 'Mojon', value: 'Mojon' },
    { label: 'Namayan', value: 'Namayan' },
    { label: 'Niugan', value: 'Niugan' },
    { label: 'Pamarawan', value: 'Pamarawan' },
    { label: 'Panasahan', value: 'Panasahan' },
    { label: 'Pinagbakahan', value: 'Pinagbakahan' },
    { label: 'San Agustin', value: 'San Agustin' },
    { label: 'San Gabriel', value: 'San Gabriel' },
    { label: 'San Juan', value: 'San Juan' },
    { label: 'San Pablo', value: 'San Pablo' },
    { label: 'San Vicente', value: 'San Vicente' },
    { label: 'Santiago', value: 'Santiago' },
    { label: 'Santisima Trinidad', value: 'Santisima Trinidad' },
    { label: 'Santo Cristo', value: 'Santo Cristo' },
    { label: 'Santo Niño', value: 'Santo Niño' },
    { label: 'Santo Rosario', value: 'Santo Rosario' },
    { label: 'Sumapang Bata', value: 'Sumapang Bata' },
    { label: 'Sumapang Matanda', value: 'Sumapang Matanda' },
    { label: 'Taal', value: 'Taal' },
    { label: 'Tikay', value: 'Tikay' },
  ],
  'San Jose del Monte City': [
    { label: 'Select Barangay', value: '' },
    { label: 'Bagong Buhay', value: 'Bagong Buhay' },
    { label: 'Citrus', value: 'Citrus' },
    { label: 'Ciudad Real', value: 'Ciudad Real' },
    { label: 'Dulong Bayan', value: 'Dulong Bayan' },
    { label: 'Fatima', value: 'Fatima' },
    { label: 'Francisco Homes-Guijo', value: 'Francisco Homes-Guijo' },
    { label: 'Francisco Homes-Mulawin', value: 'Francisco Homes-Mulawin' },
    { label: 'Francisco Homes-Narra', value: 'Francisco Homes-Narra' },
    { label: 'Francisco Homes-Yakal', value: 'Francisco Homes-Yakal' },
    { label: 'Gaya-gaya', value: 'Gaya-gaya' },
    { label: 'Graceville', value: 'Graceville' },
    { label: 'Gumaoc Central', value: 'Gumaoc Central' },
    { label: 'Gumaoc East', value: 'Gumaoc East' },
    { label: 'Gumaoc West', value: 'Gumaoc West' },
    { label: 'Kaypian', value: 'Kaypian' },
    { label: 'Lawang Pari', value: 'Lawang Pari' },
    { label: 'Maharlika', value: 'Maharlika' },
    { label: 'Minuyan I', value: 'Minuyan I' },
    { label: 'Minuyan II', value: 'Minuyan II' },
    { label: 'Minuyan III', value: 'Minuyan III' },
    { label: 'Minuyan IV', value: 'Minuyan IV' },
    { label: 'Minuyan V', value: 'Minuyan V' },
    { label: 'Muzon', value: 'Muzon' },
    { label: 'Paradise III', value: 'Paradise III' },
    { label: 'Poblacion', value: 'Poblacion' },
    { label: 'Poblacion I', value: 'Poblacion I' },
    { label: 'San Isidro', value: 'San Isidro' },
    { label: 'San Manuel', value: 'San Manuel' },
    { label: 'San Martin', value: 'San Martin' },
    { label: 'San Pedro', value: 'San Pedro' },
    { label: 'San Rafael', value: 'San Rafael' },
    { label: 'San Roque', value: 'San Roque' },
    { label: 'Santa Cruz', value: 'Santa Cruz' },
    { label: 'Santo Cristo', value: 'Santo Cristo' },
    { label: 'Santo Niño', value: 'Santo Niño' },
    { label: 'Sapang Palay', value: 'Sapang Palay' },
    { label: 'Tungkong Mangga', value: 'Tungkong Mangga' },
  ],
  // Cebu additional
  'Lapu-Lapu City': [
    { label: 'Select Barangay', value: '' },
    { label: 'Agus', value: 'Agus' },
    { label: 'Babag', value: 'Babag' },
    { label: 'Bankal', value: 'Bankal' },
    { label: 'Basak', value: 'Basak' },
    { label: 'Buaya', value: 'Buaya' },
    { label: 'Canjulao', value: 'Canjulao' },
    { label: 'Caubian', value: 'Caubian' },
    { label: 'Gun-ob', value: 'Gun-ob' },
    { label: 'Ibo', value: 'Ibo' },
    { label: 'Looc', value: 'Looc' },
    { label: 'Mactan', value: 'Mactan' },
    { label: 'Maribago', value: 'Maribago' },
    { label: 'Marigondon', value: 'Marigondon' },
    { label: 'Pajac', value: 'Pajac' },
    { label: 'Pajo', value: 'Pajo' },
    { label: 'Poblacion', value: 'Poblacion' },
    { label: 'Punta Engaño', value: 'Punta Engaño' },
    { label: 'Pusok', value: 'Pusok' },
    { label: 'Sabang', value: 'Sabang' },
    { label: 'Santa Rosa', value: 'Santa Rosa' },
    { label: 'Subabasbas', value: 'Subabasbas' },
    { label: 'Talima', value: 'Talima' },
    { label: 'Tingo', value: 'Tingo' },
    { label: 'Tungasan', value: 'Tungasan' },
  ],
  'Mandaue City': [
    { label: 'Select Barangay', value: '' },
    { label: 'Alang-alang', value: 'Alang-alang' },
    { label: 'Bakilid', value: 'Bakilid' },
    { label: 'Banilad', value: 'Banilad' },
    { label: 'Basak', value: 'Basak' },
    { label: 'Cabancalan', value: 'Cabancalan' },
    { label: 'Cambaro', value: 'Cambaro' },
    { label: 'Canduman', value: 'Canduman' },
    { label: 'Casili', value: 'Casili' },
    { label: 'Casuntingan', value: 'Casuntingan' },
    { label: 'Centro', value: 'Centro' },
    { label: 'Cubacub', value: 'Cubacub' },
    { label: 'Guizo', value: 'Guizo' },
    { label: 'Ibabao-Estancia', value: 'Ibabao-Estancia' },
    { label: 'Jagobiao', value: 'Jagobiao' },
    { label: 'Labogon', value: 'Labogon' },
    { label: 'Looc', value: 'Looc' },
    { label: 'Maguikay', value: 'Maguikay' },
    { label: 'Mantuyong', value: 'Mantuyong' },
    { label: 'Opao', value: 'Opao' },
    { label: 'Pagsabungan', value: 'Pagsabungan' },
    { label: 'Pakna-an', value: 'Pakna-an' },
    { label: 'Subangdaku', value: 'Subangdaku' },
    { label: 'Tabok', value: 'Tabok' },
    { label: 'Tawason', value: 'Tawason' },
    { label: 'Tingub', value: 'Tingub' },
    { label: 'Tipolo', value: 'Tipolo' },
    { label: 'Umapad', value: 'Umapad' },
  ],
};

// ZIP Code mapping by city
export const ZIP_CODES = {
  // NCR - Metro Manila
  'Caloocan': '1400',
  'Las Piñas': '1740',
  'Makati': '1200',
  'Malabon': '1470',
  'Mandaluyong': '1550',
  'Manila': '1000',
  'Marikina': '1800',
  'Muntinlupa': '1770',
  'Navotas': '1485',
  'Parañaque': '1700',
  'Pasay': '1300',
  'Pasig': '1600',
  'Pateros': '1620',
  'Quezon City': '1100',
  'San Juan': '1500',
  'Taguig': '1630',
  'Valenzuela': '1440',
  // Region I
  'Laoag City': '2900',
  'Batac City': '2906',
  'Vigan City': '2700',
  'Candon City': '2710',
  'San Fernando City': '2500', // La Union
  // Region III
  'Malolos City': '3000',
  'Meycauayan City': '3020',
  'San Jose del Monte City': '3023',
  'Angeles City': '2009',
  'Mabalacat City': '2010',
  'Cabanatuan City': '3100',
  'Tarlac City': '2300',
  'Olongapo City': '2200',
  'Balanga City': '2100',
  // Region IV-A (CALABARZON)
  'Bacoor City': '4102',
  'Cavite City': '4100',
  'Dasmariñas City': '4114',
  'General Trias City': '4107',
  'Imus City': '4103',
  'Tagaytay City': '4120',
  'Trece Martires City': '4109',
  'Biñan City': '4024',
  'Cabuyao City': '4025',
  'Calamba City': '4027',
  'San Pablo City': '4000',
  'San Pedro City': '4023',
  'Santa Rosa City': '4026',
  'Los Baños': '4030',
  'Batangas City': '4200',
  'Lipa City': '4217',
  'Tanauan City': '4232',
  'Antipolo City': '1870',
  'Cainta': '1900',
  'Taytay': '1920',
  'Lucena City': '4301',
  // Region VII (Central Visayas)
  'Cebu City': '6000',
  'Lapu-Lapu City': '6015',
  'Mandaue City': '6014',
  'Talisay City': '6045', // Cebu
  'Tagbilaran City': '6300',
  // Region XI (Davao)
  'Davao City': '8000',
  'Digos City': '8002',
  'Tagum City': '8100',
  'Panabo City': '8105',
};

// Helper function to get provinces by region
export const getProvincesByRegion = (region) => {
  return PROVINCES[region] || [{ label: 'Select Province', value: '' }];
};

// Helper function to get cities by province
export const getCitiesByProvince = (province) => {
  return CITIES[province] || [{ label: 'Select City/Municipality', value: '' }];
};

// Helper function to get barangays by city
export const getBarangaysByCity = (city) => {
  return BARANGAYS[city] || [{ label: 'Select Barangay', value: '' }];
};

// Helper function to auto-calculate ZIP code by city
export const getZipCodeByCity = (city) => {
  return ZIP_CODES[city] || '';
};

// Helper function to get ZIP code label for display
export const getZipCodeLabel = (city) => {
  const zipCode = ZIP_CODES[city];
  return zipCode ? zipCode : 'N/A';
};